runtime: nodejs18
env: flex

env_variables:
  NODE_ENV: "production"
  PORT: "8080"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cpu_utilization:
    target_utilization: 0.65

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
  - url: /.*
    script: auto
    secure: always

network:
  session_affinity: true 