steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/segtrack-api', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/segtrack-api']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'segtrack123'
      - '--image'
      - 'gcr.io/$PROJECT_ID/segtrack-api'
      - '--region'
      - 'southamerica-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - |
        DATABASE_URL=$_DATABASE_URL,
        NODE_ENV=production,
        JWT_SECRET=$_JWT_SECRET,
        PORT=8080
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--timeout'
      - '300s'
      - '--execution-environment'
      - 'gen2'
      - '--ingress'
      - 'all'

timeout: '1800s'
images:
  - 'gcr.io/$PROJECT_ID/segtrack-api' 