-- AlterTable
ALTER TABLE "Foto" ADD COLUMN     "cropArea" JSONB,
ADD COLUMN     "cropX" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "cropY" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "zoom" DOUBLE PRECISION DEFAULT 1;
