import { z } from 'zod';

export const ocorrenciaSchema = z.object({
  placa1: z.string(),
  placa2: z.string().nullable().optional(),
  placa3: z.string().nullable().optional(),
  modelo1: z.string().nullable().optional(),
  cor1: z.string().nullable().optional(),
  cliente: z.string(),
  tipo: z.string(),
  tipo_veiculo: z.string().nullable().optional(),
  coordenadas: z.string().nullable().optional(),
  endereco: z.string().nullable().optional(),
  bairro: z.string().nullable().optional(),
  cidade: z.string().nullable().optional(),
  estado: z.string().nullable().optional(),
  cpf_condutor: z.string().nullable().optional(),
  nome_condutor: z.string().nullable().optional(),
  transportadora: z.string().nullable().optional(),
  valor_carga: z.number().nullable().optional(),
  notas_fiscais: z.string().nullable().optional(),
  os: z.string().nullable().optional(),
  origem_bairro: z.string().nullable().optional(),
  origem_cidade: z.string().nullable().optional(),
  origem_estado: z.string().nullable().optional(),
  prestador: z.string().nullable().optional(),
  inicio: z.date().nullable().optional(),
  chegada: z.date().nullable().optional(),
  termino: z.date().nullable().optional(),
  km: z.number().nullable().optional(),
  km_inicial: z.number().nullable().optional(),
  km_final: z.number().nullable().optional(),
  despesas: z.number().nullable().optional(),
  despesas_detalhadas: z.any().nullable().optional(),
  descricao: z.string().nullable().optional(),
  resultado: z.string().nullable().optional(),
  status: z.string().default("Em andamento"),
  data_acionamento: z.date().nullable().optional(),
  fotos: z.array(z.object({
    url: z.string(),
    legenda: z.string().optional().default(''),
  })).optional(),
}); 