name: Deploy Backend SEGTRACK

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy na EC2 (backend)
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar repositório
        uses: actions/checkout@v3

      - name: 🔐 Criar chave SSH
        run: |
          echo "${{ secrets.SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: 🚀 Executar deploy backend na EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /opt/segtrack/backup
            sudo env $(cat backup.env | xargs) ./execute-deploy.sh
          EOF
